---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/MethodLength:
        enabled: false
      Rubocop/Metrics/ParameterLists:
        enabled: false
ratings:
  paths:
  - "**/*.rb"
exclude_paths:
- "*.*"
- ".*"
- "**/*.md"
- "**/*.yml"
- "*.gemspec"
- Gemfile
- LICENSE
- Rakefile
- examples/
- res/
- script/
- spec/
